home:
    path: /
    controller: App\Controller\HomeController::index

game.index:
    path: /jeux
    controller: App\Controller\GameController::index

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
